export const MOCK_COURSES_LIST = [
    { value: 'course_1', label: 'Advanced React Patterns' },
    { value: 'course_2', label: 'Testing JavaScript Applications' },
    { value: 'course_3', label: 'CSS layout for the modern web' },
    { value: 'course_4', label: 'Next.js: The Complete Guide' },
    { value: 'course_5', label: 'Generative Art with Code' },
];

export const MOCK_INSTRUCTORS_LIST = [
    { value: 'inst_1', label: 'Sarah Drasner' },
    { value: 'inst_2', label: 'Kent C. Dodds' },
    { value: 'inst_3', label: 'Dan Abramov' },
    { value: 'inst_4', label: 'Cassidy Williams' },
    { value: 'inst_5', label: 'Guillermo Rauch' },
];

export const MOCK_REPORTS_DATA = [
    {
        id: 1,
        courseName: 'Advanced React Patterns',
        courseId: 'course_1',
        participantName: 'Alice Johnson',
        instructorName: 'Sarah Drasner',
        instructorId: 'inst_1',
        enrolledDate: '2023-11-20',
        startDate: '2023-11-21',
        timeSpent: '12h 30m',
        completionPercentage: 100,
        completedDate: '2023-12-05',
        status: 'completed',
    },
    {
        id: 2,
        courseName: 'Advanced React Patterns',
        courseId: 'course_1',
        participantName: 'Bob Smith',
        instructorName: 'Sarah Drasner',
        instructorId: 'inst_1',
        enrolledDate: '2023-12-01',
        startDate: '2023-12-02',
        timeSpent: '4h 15m',
        completionPercentage: 45,
        completedDate: null,
        status: 'in-progress',
    },
    {
        id: 3,
        courseName: 'Testing JavaScript Applications',
        courseId: 'course_2',
        participantName: 'Charlie Brown',
        instructorName: 'Kent C. Dodds',
        instructorId: 'inst_2',
        enrolledDate: '2023-12-10',
        startDate: null,
        timeSpent: '0h 0m',
        completionPercentage: 0,
        completedDate: null,
        status: 'yet-to-start',
    },
    {
        id: 4,
        courseName: 'Next.js: The Complete Guide',
        courseId: 'course_4',
        participantName: 'Diana Prince',
        instructorName: 'Guillermo Rauch',
        instructorId: 'inst_5',
        enrolledDate: '2023-11-15',
        startDate: '2023-11-16',
        timeSpent: '8h 45m',
        completionPercentage: 75,
        completedDate: null,
        status: 'in-progress',
    },
    {
        id: 5,
        courseName: 'CSS layout for the modern web',
        courseId: 'course_3',
        participantName: 'Evan Wright',
        instructorName: 'Dan Abramov',
        instructorId: 'inst_3',
        enrolledDate: '2023-12-20',
        startDate: '2023-12-22',
        timeSpent: '2h 10m',
        completionPercentage: 30,
        completedDate: null,
        status: 'in-progress',
    },
    {
        id: 6,
        courseName: 'Generative Art with Code',
        courseId: 'course_5',
        participantName: 'Fiona Gallagher',
        instructorName: 'Cassidy Williams',
        instructorId: 'inst_4',
        enrolledDate: '2024-01-05',
        startDate: null,
        timeSpent: '0h 0m',
        completionPercentage: 0,
        completedDate: null,
        status: 'yet-to-start',
    },
    {
        id: 7,
        courseName: 'Testing JavaScript Applications',
        courseId: 'course_2',
        participantName: 'George Miller',
        instructorName: 'Kent C. Dodds',
        instructorId: 'inst_2',
        enrolledDate: '2023-11-01',
        startDate: '2023-11-02',
        timeSpent: '15h 00m',
        completionPercentage: 100,
        completedDate: '2023-11-25',
        status: 'completed',
    },
    {
        id: 8,
        courseName: 'Next.js: The Complete Guide',
        courseId: 'course_4',
        participantName: 'Hannah Montana',
        instructorName: 'Guillermo Rauch',
        instructorId: 'inst_5',
        enrolledDate: '2023-12-15',
        startDate: '2023-12-16',
        timeSpent: '1h 30m',
        completionPercentage: 10,
        completedDate: null,
        status: 'in-progress',
    },
    {
        id: 9,
        courseName: 'Advanced React Patterns',
        courseId: 'course_1',
        participantName: 'Ian Somerhalder',
        instructorName: 'Sarah Drasner',
        instructorId: 'inst_1',
        enrolledDate: '2024-01-10',
        startDate: null,
        timeSpent: '0h 0m',
        completionPercentage: 0,
        completedDate: null,
        status: 'yet-to-start',
    },
    {
        id: 10,
        courseName: 'CSS layout for the modern web',
        courseId: 'course_3',
        participantName: 'Jack Dawson',
        instructorName: 'Dan Abramov',
        instructorId: 'inst_3',
        enrolledDate: '2023-10-10',
        startDate: '2023-10-12',
        timeSpent: '6h 00m',
        completionPercentage: 100,
        completedDate: '2023-10-20',
        status: 'completed',
    }
];
